using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Controll : MonoBehaviour
{
    private CharacterController characterController;
    private Animator animator;
    private Vector3 movimiento = Vector3.zero;

    public new Transform camera; 
    public float speed = 4;
    public float gravity = 9.8f;
    public float fallVelocity;
    public float jumpForce;
    
    
    
    void Start()
    {
        characterController = GetComponent<CharacterController>();
        animator = GetComponent<Animator>();
    }

    void Update()
    {
        SetGravity();
        PlayerSkills();

        float hor = Input.GetAxis("Horizontal");
        float ver = Input.GetAxis("Vertical");
        Vector3 movement = Vector3.zero;
        float movementSpeed = 0;
        

        if(hor !=0 || ver != 0)
        {
            Vector3 forward = camera.forward;
            forward.y = 0;
            forward.Normalize();

            Vector3 right = camera.right;
            right.y = 0;
            right.Normalize();
            
            Vector3 direction = forward * ver + right * hor;
            movementSpeed = Mathf.Clamp01(direction.magnitude);
            direction.Normalize();

            movement = direction * speed * Time.deltaTime;

            transform.rotation = Quaternion.Slerp(transform.rotation, Quaternion.LookRotation(direction), 0.8f);
        }

        movement.y += gravity * Time.deltaTime;
        characterController.Move(movement);
        animator.SetFloat("Mag", movementSpeed);

        
    }

    public void PlayerSkills()
    {
        if(characterController.isGrounded && Input.GetButtonDown("Jump"))
        {
            fallVelocity = jumpForce;
            movimiento.y = fallVelocity;
        }
    }

    public void SetGravity()
    {
        
        if(characterController.isGrounded)
        {
            fallVelocity = -gravity * Time.deltaTime;
            movimiento.y = fallVelocity;
        }
        else
        {
            fallVelocity -= gravity * Time.deltaTime;
            movimiento.y = fallVelocity;
        }
    }

}

